### ISSUE TITLE
Successful result from ContainerUtilities are missing/ambiguous

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1071]
When I successfully select container data using the CONTAINERUTILITIES, there is no message that results were successfully retrieved..   A message that request succeeded, possibly with the location of the output file would be very nice. (at least the name of the file).

**Comment by ligadata-dhaval** [comment]
Facing similar doubts

**Comment by ligadata-yousef** [comment]
fixed, check it please

**Comment by ligadata-dan** [comment]
@ligadata-yousef 

Hi Yusef, Diaval is seeing a corrupt file being externalized into the file

**Comment by ligadata-dan** [comment]
@ligadata-dhaval 
 
Please add your findings to this

**Comment by ligadata-dhaval** [comment]
I am getting the below result when I open the .dat file:
��?
   �0�w?��Ғ������`bz6m��N��;�k9[uK��pt4	�i�@��T�-c<岤�IcI�\�:�%{0n��T�m��_�l�Ŭ����pX�E������'���*��/��I��m�;K"H��hx��%�Mc��&��>ۗ�O~���f

Can we have a txt file instead?

Also, result is coming as warning.

**Comment by ligadata-yousef** [comment]
i don't know why you see that result , below is my result:

0330,\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\"
0331,\"0331 - Whooping cough due to bordetella parapertussis [B. parapertussis]\"
0338,\"0338 - Whooping cough due to other specified organism\"
0339,\"0339 - Whooping cough
4843,\"4843 - Pneumonia in whooping cough\"
7868,\"7868 - Hiccough\"
33983,\"33983 - Primary cough headache\"


and for result on warn, i wrote an info but Pokuri told me to change it to warn because there is a lot of info when tool run like create connection ....etc.

**Comment by ligadata-dhaval** [comment]
Could you print the results as well along with WARN?

**Comment by ligadata-pokuri** [comment]
Hi Dhaval,
Where do we need to print results? Only status we need to give with println/INFO. The real data should go to file.

**Comment by ligadata-dhaval** [comment]
Yes, I meant the status which we are showing as WARN as of now

**Comment by ligadata-dhaval** [comment]
Yousef and I checked and the code is working when compresssionstring is empty instead of gz. Maybe we need to update the code such that when a gz compression is given the output file is also a gz instead of dat.

**Comment by ligadata-yousef** [comment]
fixed.

**Comment by ligadata-dhaval** [comment]
Verified
