### ISSUE TITLE
CONTAINERUTILITIES:  Needs to document FILTER file behavior.

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1073]
What is the relationships between each element in this array.  Are they OR or AND conditions?

This needs to be very clearly defined..  For example, in the JSON below, would we expect the result from the FILTER ELEMENT 1, 2, and 3  to go through the AND or OR logic? 

At this point it looks like its an OR (**but duplicates are not purged from the resul**t)

[
  { ** <=========== FILTER ELEMENT 1**
    "begintime": "20150612110312",
    "endtime": "20150612110412",
    "keys": [
      ["1", "2", "3"]
    ]
  },
  {** <=========== FILTER ELEMENT 2**
    "begintime": "20150612110312",
    "endtime": "20150612110412",
    "keys": [
      ["1", "2", "3"],
      ["12", "222", "333"]
    ]
  },
  {** <=========== FILTER ELEMENT 3**
    "begintime": "20150612110312",
    "endtime": "20150612110412"
  }
]

**Comment by ligadata-pokuri** [comment]
Yousef, give some meaningful key in the document. You can take one of the container from Medical sample and give those examples or something like that instead of "1", "2", "3"

**Comment by ligadata-yousef** [comment]
for begintime and endtime the relational is AND.
for heys the relational is OR.

for example the FILTER ELEMENT 2 means:

delete/select the data from container where
 begintime =  "20150612110312" and endtime = "20150612110412" 
and (key = ["1", "2", "3"] or key = ["12", "222", "333"]);

i will send a document with all cases as soon as possible.


note: this is a real example from medical containers:

suppose that use a container from medical such as com.ligadata.kamanja.samples.containers.CoughtCodes
the key will be the column ic9code
for example 

"keys":[
["0330"],
["0331"]
]

you can find the value of key inside CoughCodes_medical.dat in first column
and for timeranges till now kamanja put all data into timerange(0,0).

make sure to push some data before you check tool if you want to see a result.

**Comment by ligadata-dan** [comment]
@ligadata-yousef 

What about the relationship between objets in the array.    In the original example, the FilterElement X.  I use the Medical Container values to test it.

If it is an OR..  do we need purge duplicates  from the result set?

**Comment by ligadata-yousef** [comment]
there is no  relationship between object elements. this tool take each element  separately  so if you need to delete/select data from container for one key and two discrete timeranges you should do like below:
[
{** <=========== FILTER ELEMENT 1**
"begintime": "2015",
"endtime": "2016",
"keys": [
["1", "2", "3"],
["12", "222", "333"]
]
},
{** <=========== FILTER ELEMENT 2**
"begintime": "2017",
"endtime": "2018"
"keys": [
["1", "2", "3"],
["12", "222", "333"]
]
}
]

**Comment by ligadata-dhaval** [comment]
Hi,

I used the below filter.json:

[
     {
       "begintime": "0",
       "endtime": "0"
     }
     ,
     {
       "begintime": "0",
       "endtime": "0"
     }
   ]

As it can be seen, it has the filter criteria twice which is why I get the below result:

4843,\"4843 - Pneumonia in whooping cough\"
7868,\"7868 - Hiccough\"
33983,\"33983 - Primary cough headache\"
0331,\"0331 - Whooping cough due to bordetella parapertussis [B. parapertussis]\"
0330,\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\"
0338,\"0338 - Whooping cough due to other specified organism\"
0339,\"0339 - Whooping cough
4843,\"4843 - Pneumonia in whooping cough\"
7868,\"7868 - Hiccough\"
33983,\"33983 - Primary cough headache\"
0331,\"0331 - Whooping cough due to bordetella parapertussis [B. parapertussis]\"
0330,\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\"
0338,\"0338 - Whooping cough due to other specified organism\"
0339,\"0339 - Whooping cough

The result I get twice. Is this the expected functionality or should it be there only once?

**Comment by ligadata-pokuri** [comment]
For now we can document this is expected behavior. i.e. for every key we pull data once.

**Comment by ligadata-pokuri** [comment]
Dhaval, make sure we document as NOTE in this utility documentation

**Comment by ligadata-dhaval** [comment]
Hi Alison,

Kindly could you add a note that if filter.json contains more than one criteria they will act individually and give results independent of each other.

e.g.

Consider the below filter.json for select criteria:

[
{
"begintime": "0",
"endtime": "0"
}
,
{
"begintime": "0",
"endtime": "0"
}
]

Both will return results independently and in this case the same result is shown twice.

4843,\"4843 - Pneumonia in whooping cough\"
7868,\"7868 - Hiccough\"
33983,\"33983 - Primary cough headache\"
0331,\"0331 - Whooping cough due to bordetella parapertussis [B. parapertussis]\"
0330,\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\"
0338,\"0338 - Whooping cough due to other specified organism\"
0339,\"0339 - Whooping cough
4843,\"4843 - Pneumonia in whooping cough\"
7868,\"7868 - Hiccough\"
33983,\"33983 - Primary cough headache\"
0331,\"0331 - Whooping cough due to bordetella parapertussis [B. parapertussis]\"
0330,\"0330 - Whooping cough due to bordetella pertussis [B. pertussis]\"
0338,\"0338 - Whooping cough due to other specified organism\"
0339,\"0339 - Whooping cough

Please let me know if any issues or questions and we can rephrase the statements, if needed.

**Comment by ligadata-alison** [comment]
I have updated the documentation:

http://kamanja.org/administration-monitoring-1-4/containersutility-1-4/

Please take a look and close if it's ok.

**Comment by ligadata-dan** [comment]
@ligadata-alison  

 Can you add an explicit comment to the POINT 5

...**(as a result you may see duplicate values in the output file)**

@ligadata-yousef 
Hi Yousef,  chatted with pokuri, and maybe in the next release, we can externalize the result for each filter criteria to a different file.

**Comment by ligadata-alison** [comment]
Hi Dan,
     Please verify.

http://kamanja.org/administration-monitoring-1-4/containersutility-1-4/

thanks,
alison

**Comment by ligadata-alison** [comment]
closing

**Comment by ligadata-dan** [comment]
@ligadata-alison 

Looks good
