### ISSUE TITLE
JTM - Compilation Errors when using Mapped Messages

### ISSUE THREAD

**Issue by ligadata-tulasi** [LigaData/Kamanja#1099]
Getting the following errors while adding medical jtm (for mapped messages) 

/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:60: error: value sp_copd is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.sp_copd = conversion.ToInteger(inpData(20))
               ^
/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:61: error: value aatdeficiency is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.aatdeficiency = conversion.ToInteger(inpData(84))
               ^
/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:62: error: value weight is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.weight = conversion.ToDouble(inpData(76))
               ^
/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:63: error: value injury_poisoning is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.injury_poisoning = conversion.ToInteger(inpData(44))
               ^
/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:64: error: value atrial_fibrillation is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.atrial_fibrillation = conversion.ToInteger(inpData(53))
               ^
/data/1.4.0.Messages/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:65: error: value diseases_skin_subcutaneous_tissue is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.diseases_skin_subcutaneous_tissue = conversion.ToInteger(inpData(39))

**Comment by ligadata-pokuri** [comment]
[test.zip](https://github.com/LigaData/Kamanja/files/246295/test.zip)

**Comment by ligadata-tulasi** [comment]
The attached zip file consists the mapped messages , model and jtm used in testing and also the generated jtm scala file.

**Comment by ligadata-pokuri** [comment]
Hi joerg,

After doing these commands i still see issues. It is just generating code with . notation instead of set


$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $KAMANJA_HOME/input/SampleApplications/metadata/message/COPDInputMessage.json TENANTID tenant1

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $KAMANJA_HOME/input/SampleApplications/metadata/message/beneficiary_Medical.json TENANTID tenant1

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $KAMANJA_HOME/input/SampleApplications/metadata/message/hl7_Medical.json TENANTID tenant1

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $KAMANJA_HOME/input/SampleApplications/metadata/message/inpatientclaim_Medical.json TENANTID tenant1

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $KAMANJA_HOME/input/SampleApplications/metadata/message/outpatientclaim_Medical.json TENANTID tenant1

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties upload compile config $KAMANJA_HOME/config/COPDRiskAssessmentCompileCfg.json

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add model jtm $KAMANJA_HOME/input/SampleApplications/metadata/model/COPDDataIngest.jtm DEPENDSON COPDDataIngest TENANTID tenant1

**Comment by ligadata-pokuri** [comment]
data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:50: error: value msg is not a member of com.ligadata.kamanja.samples.messages.V1000001.COPDInputMessage
      val inpData: Array[String] = msg1.msg.split(",", -1)
                                        ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:60: error: value sp_copd is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.sp_copd = conversion.ToInteger(inpData(20))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:61: error: value aatdeficiency is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.aatdeficiency = conversion.ToInteger(inpData(84))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:62: error: value weight is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.weight = conversion.ToDouble(inpData(76))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:63: error: value injury_poisoning is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.injury_poisoning = conversion.ToInteger(inpData(44))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:64: error: value atrial_fibrillation is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.atrial_fibrillation = conversion.ToInteger(inpData(53))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:65: error: value diseases_skin_subcutaneous_tissue is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.diseases_skin_subcutaneous_tissue = conversion.ToInteger(inpData(39))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:66: error: value hypothyroidism is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.hypothyroidism = conversion.ToInteger(inpData(47))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:67: error: value hyperlipidemia is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.hyperlipidemia = conversion.ToInteger(inpData(63))
               ^
/data/Kamanja/Kamanja-1.4.0_2.11/workingdir/COPDDataIngest/COPDDataIngest.scala:68: error: value sp_osteoprs is not a member of com.ligadata.kamanja.samples.messages.V1000000.HL7
        result.sp_osteoprs = conversion.ToInteger(inpData(24))
               ^

**Comment by ligadata-pokuri** [comment]
Tulasi, verify this

**Comment by ligadata-tulasi** [comment]
Verified, closing.
