### ISSUE TITLE
KPMML and PMML Model update fails 

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1110]
kamanja update fails on KPMML Model 
Result: {
"APIResults" : {
"Status Code" : -1,
"Function Name" : "UpdateModel(type = KPMML)",
"Result Data" : null,
"Result Description" : "Failed to Update Model. Model with higher version required than any previous version including removed models:system.helloworld.000001000005000002"
}
}

pmml model update fails

Result: {
"APIResults" : {
"Status Code" : -1,
"Function Name" : "UpdateModel(type = PMML)",
"Result Data" : null,
"Result Description" : "The model name and new version was not supplied for this PMML model : name= version=null\nOptionally one should consider supplying the exact version of the model being updated, especially important when you are maintaining multiple versions with the same model name and tweaking versions of same for your 'a/b/c...' score comparisons."
}
}
 @ligadatahari
               
Write

**Comment by ligadata-dan** [comment]
@ligadata-pokuri @ligadata-rich 

Hi Guys, per our conversion  creating and assigning the PMML part to Rich, I will take a look at KPMML

**Comment by ligadata-rich** [comment]
The pmml update expects the full message name with version to be retrieved.  With the advent of the  inputMsgSets.message only contains the FullName portion (i.e., the namespace.name) of the message name.  I think we can use the inputMsgSets.message to just look up the metadata for the message and then get the fullname with version. 

It should work as before by doing that.  

I wouldn't be surprised if the other kpmml is something related to the inputMsgSets integration as well.

**Comment by ligadata-dan** [comment]
@ligadatahari 

The KPMML part seems to work.

Dans-MacBook-Pro-2:bin dankozin$ ./kamanja update model kpmml tenantid tenant1
Using default configuration /Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/config/MetadataAPIConfig.properties
 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - DATABASE remains unset
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
ERROR [main] - Node Undefined not found in metadata

Pick a Model Definition file(s) from below choices

[1]/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampleApplications/metadata/model/COPDRiskAssessmentv2_Medical.xml
[2]/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml

Enter your choice(If more than 1 choice, please use commas to seperate them):
2
User selected the option(s) 1
added manifest
adding: HelloWorld.scala(in = 13198) (out= 3316)(deflated 74%)
adding: HelloWorld.xml(in = 2858) (out= 1059)(deflated 62%)
adding: System/(in = 0) (out= 0)(stored 0%)
adding: System/HelloWorld$$anonfun$1.class(in = 1435) (out= 769)(deflated 46%)
adding: System/HelloWorld$$anonfun$2.class(in = 1645) (out= 869)(deflated 47%)
adding: System/HelloWorld$$anonfun$3.class(in = 2978) (out= 1374)(deflated 53%)
adding: System/HelloWorld$Derive_ScoreCheck.class(in = 3185) (out= 1280)(deflated 59%)
adding: System/HelloWorld$RuleSetModel_classification_02$$anonfun$execute$1$$anonfun$apply$mcV$sp$1.class(in = 2412) (out= 1047)(deflated 56%)
adding: System/HelloWorld$RuleSetModel_classification_02$$anonfun$execute$1.class(in = 1981) (out= 857)(deflated 56%)
adding: System/HelloWorld$RuleSetModel_classification_02.class(in = 2477) (out= 1055)(deflated 57%)
adding: System/HelloWorld$SimpleRule_ScoreCheck_01.class(in = 1742) (out= 848)(deflated 51%)
adding: System/HelloWorld.class(in = 14403) (out= 6919)(deflated 51%)
adding: System/HelloWorldFactory$$anonfun$isValidMessage$1.class(in = 1589) (out= 810)(deflated 49%)
adding: System/HelloWorldFactory.class(in = 2998) (out= 1704)(deflated 43%)
 WARN [main] - Not Notifying the engine about this operation because The property NOTIFY_ENGINE is not set to YES
 WARN [main] - Not Notifying the engine about this operation because The property NOTIFY_ENGINE is not set to YES
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:system.helloworld.000000000001000004"
  }
}

**Comment by ligadata-rich** [comment]
rich@pepper:~/github/dev/1.4.0.Base/kamanja/trunk$ git commit -am "issue 1110 update pmml model"
[issue1085 5a7a074] issue 1110 update pmml model
 1 file changed, 7 insertions(+), 1 deletion(-)
rich@pepper:~/github/dev/1.4.0.Base/kamanja/trunk$ git push origin issue1085
Password for 'https://ligadata-rich@github.com':

**Comment by ligadatahari** [comment]
it appears as fixed
