### ISSUE TITLE
PushSampleDataToKafka_XXXXX looking for kerberos config file even for plaintext 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1251]
Please select from the above options: 11
User selected: /opt/kamanja/Kamanja-1.4.1_2.11/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz
Exception in thread "main" java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:91)
	at scala.io.Source$.fromFile(Source.scala:76)
	at scala.io.Source$.fromFile(Source.scala:54)
	at com.ligadata.tools.SimpleKafkaProducer$.main(SimpleKafkaProducer.scala:545)
	at com.ligadata.tools.SimpleKafkaProducer.main(SimpleKafkaProducer.scala)

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Hi Saleh,  the issue here is that its looking for a nput_Data_HelloWorld.csv.gz but in the a/Kamanja-1.4.1_2.11/ directory - which doesn't exist.  The Kamanja645 branch still had 1.4.1  but Looks like your install script was from the 1.5.0.Test  which has the correct directory...

I think its a build issue that should be resolved once you pull the latest.  

Please verify..  I am seeing this

Dans-MacBook-Pro-2:bin dankozin$ bash PushSampleDataToKafka_HelloWorld.sh
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/dankozin/kamanja13/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/dankozin/kamanja13/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
932 [WARN] ProducerConfig: The configuration buffer.size = 67108864 was supplied but isn't a known config.
932 [WARN] ProducerConfig: The configuration producer.type = async was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration message.send.max.retries = 3 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration batch.num.messages = 1024 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration request.required.acks = 1 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration queue.time = 50 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration socket.receive.buffer = 67108864 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration socket.send.buffer = 67108864 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration compression.codec = 0 was supplied but isn't a known config.
933 [WARN] ProducerConfig: The configuration queue.size = 16777216 was supplied but isn't a known config.
Tid: 0, Time:1466967254695ms, Lines:      51, Read:            562, Sent:            562, Last, file:/Users/dankozin/kamanja13/Kamanja-1.5.0_2.11/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz
00. File:/Users/dankozin/kamanja13/Kamanja-1.5.0_2.11/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz ElapsedTime:129.33ms
Done. ElapsedTime:210.34ms
Dans-MacBook-Pro-2:bin dankozin$

**Comment by ligadata-saleh** [comment]
verify
