### ISSUE TITLE
Error messages from the code base are confusing to users.

### ISSUE THREAD

**Issue by donald-ligadata** [ligaDATA/Kamanja#825]
Alison asked about some error messages she was seeing and Rich responded:

This is a painful thing to maintain.  Some script should be developed to scan the scala and java files looking for log4j uses (e.g., [A-Za-z0-9_]+\.{error|info|warn|debug|trace} ) to pull these and clean them up so that they can be periodically merged to this page.  If the error doesn't explain what the semantics are, then perhaps the error message content should be improved.  Another approach would be to scan logs looking for errors and doing a "uniq" on them.  This could be incorporated into the test harness perhaps.

This is expanded and discussed in the forum in the topic:
https://groups.google.com/a/ligadata.com/forum/?hl=en#!topic/kamanja/-iD0hI7mVIk

It may be possible to document this as an interim fix.

**Comment by ligadata-william** [comment]
While I agree with the statement here, the scope of this issue is too generic. What needs to happen is a single issue opened for each instance of an error message encountered by a user. There is no way to properly track it if it's all lumped into a single issue like this.

If there is a specific error message that is confusing to users, please open a separate issue with the error message seen, a list of repro steps that caused that error message to appear and an example error message that you believe would be an improvement.
